"""
检查定义数据文件 — 10 个阶段的压力测试检查项。

当前定义依据仓库内已重写的阶段文档、内容框架和模板整理。
每条检查包含：id, stage, category, description, source_ref, fail_action, result_type, score_range, required。
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# 聚合评分阈值
# ---------------------------------------------------------------------------

KILLER_TEST_THRESHOLDS = {"fail": (0, 3), "rework": (4, 5), "pass": (6, 8)}
SCENE_PT_THRESHOLDS = {"fail": (0, 3), "risk": (4, 6), "pass": (7, 10)}

# ---------------------------------------------------------------------------
# 阶段检查定义
# ---------------------------------------------------------------------------

STAGE_CHECKS: list[dict[str, Any]] = [
    # =====================================================================
    # 8.1 Intake / Idea Fission（脑洞阶段）— 新增 4 项
    # =====================================================================
    {
        "id": "intake_new_1",
        "stage": "intake",
        "category": "new",
        "description": "准入复查 — 当前题材和卡片边界是否触线，是否需要先停在 review_required / hold",
        "source_ref": "PROJECT_RULES.md §2-§3 / templates/project/IDEA_CARD.md",
        "fail_action": "回到卡片层重判，必要时 hold 或换方向",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "intake_new_2",
        "stage": "intake",
        "category": "new",
        "description": "卡片成立度 — 原始脑洞是否已经整理到可判断的 IDEA_CARD，且 `primary_motif`、`must_have`、`must_avoid` 说得清",
        "source_ref": "AI_WRITING_SOP.md：接口层 IDEA_CARD / templates/project/IDEA_CARD.md",
        "fail_action": "先补卡片字段，再谈后续阶段",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "intake_new_3",
        "stage": "intake",
        "category": "new",
        "description": "同类差异 — `primary_motif` 是否足够稳定，能否与同类题材拉开区别",
        "source_ref": "CONTENT_FRAMEWORK.md：共用母题成立标准 / 母题变体总原则",
        "fail_action": "收束母题或回到上游重判",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "intake_new_4",
        "stage": "intake",
        "category": "new",
        "description": "读者抓手 — 当前卡片是否已经有可用的情绪、冲突或信息差抓手",
        "source_ref": "CONTENT_FRAMEWORK.md：共用母题成立标准 / AI_WRITING_SOP.md：阶段 0.3",
        "fail_action": "补抓手或标 review_required",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.2 Killer Test — 原有 4 问（评分型）+ 新增 6 项
    # =====================================================================
    {
        "id": "kt_K1",
        "stage": "killer_test",
        "category": "original",
        "description": "变化过程 — 这个想法是否自带一个会发生变化的推进过程",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.3 / CONTENT_FRAMEWORK.md",
        "fail_action": "若没有变化过程就回到卡片层重构",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_K2",
        "stage": "killer_test",
        "category": "original",
        "description": "冲突骨架 — 冲突是否来自母题发动机，而不是作者硬造",
        "source_ref": "CONTENT_FRAMEWORK.md：共用母题成立标准",
        "fail_action": "若冲突骨架不稳就回修母题",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_K3",
        "stage": "killer_test",
        "category": "original",
        "description": "展开能力 — 一句话脑洞能否自然长成场景和结构",
        "source_ref": "templates/project/02_Structure.md",
        "fail_action": "若只能停在一句话，就回到结构前重想",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_K4",
        "stage": "killer_test",
        "category": "original",
        "description": "伪装识别 — 是否只是靠宿命感、悲伤感或高级感包装，实际发动机不足",
        "source_ref": "PROJECT_RULES.md §6 / CONTENT_FRAMEWORK.md",
        "fail_action": "回修发动机，不要靠包装硬推",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_new_1",
        "stage": "killer_test",
        "category": "new",
        "description": "卡片准入 — raw_idea 是否已经整理到可判断的卡片锚点，而不是直接拿脑洞开写",
        "source_ref": "templates/project/IDEA_CARD.md / PROJECT_RULES.md §2",
        "fail_action": "先补成可判断卡片，再进入后续阶段",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_2",
        "stage": "killer_test",
        "category": "new",
        "description": "人物动机 — 想要什么、为什么想要能否说清",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / templates/project/IDEA_CARD.md",
        "fail_action": "补动机到一句话可判断",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_3",
        "stage": "killer_test",
        "category": "new",
        "description": "因果支撑 — 核心冲突是否依赖空降信息、巧合或作者补丁",
        "source_ref": "CONTENT_FRAMEWORK.md / AI_WRITING_SOP.md：阶段 0.5",
        "fail_action": "补因果链，不要靠后文兜底",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_4",
        "stage": "killer_test",
        "category": "new",
        "description": "共鸣落点 — 是否能落到明确处境，让读者理解并站队",
        "source_ref": "CONTENT_FRAMEWORK.md：共用母题成立标准",
        "fail_action": "调人物处境或回修母题",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_5",
        "stage": "killer_test",
        "category": "new",
        "description": "边界复查 — 现在该继续、回修、hold 还是 reject",
        "source_ref": "PROJECT_RULES.md §2-§3 / templates/project/IDEA_CARD.md",
        "fail_action": "按边界分流，不要硬往前推",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_6",
        "stage": "killer_test",
        "category": "new",
        "description": "母题差异化 — `primary_motif` 是否足以支撑持续展开",
        "source_ref": "CONTENT_FRAMEWORK.md：母题变体总原则",
        "fail_action": "收束或重定主母题",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.3 Premise Test — 原有 5 问 + 新增 4 项
    # =====================================================================
    {
        "id": "pt_P1",
        "stage": "premise_test",
        "category": "original",
        "description": "谁想达成什么",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / templates/project/IDEA_CARD.md",
        "fail_action": "补主角目标到可判断",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P2",
        "stage": "premise_test",
        "category": "original",
        "description": "为什么非要这么做",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / CONTENT_FRAMEWORK.md",
        "fail_action": "补必要性，不要只给愿望",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P3",
        "stage": "premise_test",
        "category": "original",
        "description": "为什么不能用更简单的办法",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / PROJECT_RULES.md §6",
        "fail_action": "堵住简单解，再继续往下",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P4",
        "stage": "premise_test",
        "category": "original",
        "description": "相关人为什么会配合",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / CONTENT_FRAMEWORK.md",
        "fail_action": "补配角动机和交换条件",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P5",
        "stage": "premise_test",
        "category": "original",
        "description": "主角为什么不能直接离开、报警或求助",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / PROJECT_RULES.md §3",
        "fail_action": "堵退路，必要时回到 hold 或 reject",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_1",
        "stage": "premise_test",
        "category": "new",
        "description": "转折前因 — 关键转折是否有前因支撑",
        "source_ref": "AI_WRITING_SOP.md：阶段 0.5 / CONTENT_FRAMEWORK.md",
        "fail_action": "补铺垫，不要靠巧合硬推",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_2",
        "stage": "premise_test",
        "category": "new",
        "description": "反作用力 — 主角是否会挣扎、反抗或改写局势",
        "source_ref": "CONTENT_FRAMEWORK.md：共用母题成立标准 / AI_WRITING_SOP.md：阶段 0.5",
        "fail_action": "补反作用力，不要写成单向听话",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_3",
        "stage": "premise_test",
        "category": "new",
        "description": "变化空间 — 起点到终点是否真的能变",
        "source_ref": "CONTENT_FRAMEWORK.md：母题变体总原则",
        "fail_action": "调人物起点、终点或母题承载方式",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_4",
        "stage": "premise_test",
        "category": "new",
        "description": "人物完整性 — 主角是否有优点、缺点与明确选择",
        "source_ref": "templates/project/IDEA_CARD.md / AI_WRITING_SOP.md：阶段 0.5",
        "fail_action": "补人物完整性，再往下推",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.4 Evaluation — 原有 4 项 + 新增 5 项
    # =====================================================================
    {
        "id": "eval_E1",
        "stage": "evaluation",
        "category": "original",
        "description": "卡片价值 — 这条路线是否值得进入结构",
        "source_ref": "AI_WRITING_SOP.md：阶段 2 / templates/project/IDEA_CARD.md",
        "fail_action": "回卡片层确认是否继续",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_E2",
        "stage": "evaluation",
        "category": "original",
        "description": "冲突张力 — 是否能持续加压而不靠硬拐",
        "source_ref": "CONTENT_FRAMEWORK.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "补冲突层次或重定结构",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_E3",
        "stage": "evaluation",
        "category": "original",
        "description": "情绪承诺 — 能提供什么可回收的情绪体验",
        "source_ref": "CONTENT_FRAMEWORK.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "明确情绪定位和回收点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_E4",
        "stage": "evaluation",
        "category": "original",
        "description": "执行风险 — 是否容易滑向便利推进、角色工具化、提纲 prose",
        "source_ref": "PROJECT_RULES.md §6 / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "先标风险点，再决定 rework 还是 reject",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_1",
        "stage": "evaluation",
        "category": "new",
        "description": "母题拥挤度 — 同类中是否还有清晰差异",
        "source_ref": "CONTENT_FRAMEWORK.md：母题变体总原则",
        "fail_action": "调差异化角度或回到上游重判",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_2",
        "stage": "evaluation",
        "category": "new",
        "description": "继续投入判断 — 这条路线该进结构、回卡片，还是停在 hold",
        "source_ref": "PROJECT_RULES.md §2-§3 / AI_WRITING_SOP.md：阶段 2",
        "fail_action": "按边界分流，不要硬推进",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_3",
        "stage": "evaluation",
        "category": "new",
        "description": "平台对齐 — `target_platform` 是否已明确且与写法基线一致",
        "source_ref": "CONTENT_FRAMEWORK.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "先把平台对齐，再决定是否继续",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_4",
        "stage": "evaluation",
        "category": "new",
        "description": "体量匹配 — 这条路线是否与预期篇幅和阶段产物匹配",
        "source_ref": "AI_WRITING_SOP.md：阶段 2 / templates/project/02_Structure.md",
        "fail_action": "调整体量或回卡片层收束",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_5",
        "stage": "evaluation",
        "category": "new",
        "description": "结构准备度 — 是否已经收束到足以进入 Structure",
        "source_ref": "AI_WRITING_SOP.md：阶段 2 / templates/project/01_Evaluation_Log.md",
        "fail_action": "未收束就留在 evaluation 层 rework",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.5 Structure — 原有 5 项 + 新增 6 项
    # =====================================================================
    {
        "id": "struct_S1",
        "stage": "structure",
        "category": "original",
        "description": "结构骨架 — 核心冲突、开篇爆点、30% 卡点、中段升级、终局回收是否齐备",
        "source_ref": "templates/project/02_Structure.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "补齐缺失节点，再看是否需要 rework",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S2",
        "stage": "structure",
        "category": "original",
        "description": "人物驱动 — 大转折是否由人物选择推动，而不是作者安排",
        "source_ref": "templates/project/02_Structure.md / AI_WRITING_SOP.md：阶段 3",
        "fail_action": "改成人物驱动，必要时回修结构",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S3",
        "stage": "structure",
        "category": "original",
        "description": "情绪曲线 — E1 初始→E2 扰动→E3 升级→E4 峰值→E5 余味是否对齐",
        "source_ref": "templates/project/02_Structure.md",
        "fail_action": "调节点位置，避免情绪线断裂",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S4",
        "stage": "structure",
        "category": "original",
        "description": "行为模式 — 核心人物的行为模式、偏向和禁区是否清楚",
        "source_ref": "templates/project/02_Structure.md / templates/project/IDEA_CARD.md",
        "fail_action": "补人物行为表，必要时回到卡片层",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S5",
        "stage": "structure",
        "category": "original",
        "description": "motif 回扣 — `primary_motif` / `must_have` 是否有首次出现和回扣位置",
        "source_ref": "templates/project/02_Structure.md / CONTENT_FRAMEWORK.md",
        "fail_action": "补伏笔表，别让主发动机断掉",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_1",
        "stage": "structure",
        "category": "new",
        "description": "结构展开 — 是否已经把卡片锚点落到开篇、升级和回收",
        "source_ref": "templates/project/02_Structure.md",
        "fail_action": "调结构，不要只堆概念",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_2",
        "stage": "structure",
        "category": "new",
        "description": "单主线推进 — 是否围绕主母题形成单线推进，而不是被并行线稀释",
        "source_ref": "CONTENT_FRAMEWORK_structure.md / templates/project/02_Structure.md",
        "fail_action": "收束并行线，保留主发动机",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_3",
        "stage": "structure",
        "category": "new",
        "description": "关键截点 — 场景或章节断点是否落在已确认的结构节点",
        "source_ref": "templates/project/02_Structure.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "调场景顺序或回修结构节点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_4",
        "stage": "structure",
        "category": "new",
        "description": "持续加压 — 中段是否存在连续高潮或空转",
        "source_ref": "CONTENT_FRAMEWORK_structure.md / templates/project/02_Structure.md",
        "fail_action": "插入过渡或回修中段",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_5",
        "stage": "structure",
        "category": "new",
        "description": "因果铺垫 — 关键伏笔是否已在结构中预设并可回收",
        "source_ref": "templates/project/02_Structure.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "补伏笔位置，不要只留摆设",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_6",
        "stage": "structure",
        "category": "new",
        "description": "承载方式 — 结构是否为场景化展开留出足够承载，而不是把表达比例写死",
        "source_ref": "CONTENT_FRAMEWORK.md / templates/project/02_Structure.md",
        "fail_action": "调场景类型分布或回修结构承载",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.6 Outline — 原有 5 项 + 新增 9 项
    # =====================================================================
    {
        "id": "outline_O1",
        "stage": "outline",
        "category": "original",
        "description": "人物关系和关键动机梳理",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "补关系线和动机线",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O2",
        "stage": "outline",
        "category": "original",
        "description": "每段承担的功能标注（推进冲突/释放爽点/揭露信息/制造钩子）",
        "source_ref": "templates/project/03_Outline.md",
        "fail_action": "补功能标注，别让段落空跑",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O3",
        "stage": "outline",
        "category": "original",
        "description": "标出最容易写空、写成概述的地方",
        "source_ref": "templates/project/03_Outline.md / PROJECT_RULES.md §6",
        "fail_action": "提前标注风险并安排试写验证",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O4",
        "stage": "outline",
        "category": "original",
        "description": "每场景时间线、情绪位置入/出",
        "source_ref": "templates/project/03_Outline.md",
        "fail_action": "补场景情绪标注",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O5",
        "stage": "outline",
        "category": "original",
        "description": "认知差追踪表（主角/读者/其他角色各知道什么）",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "补认知差表，不要让信息差失控",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_1",
        "stage": "outline",
        "category": "new",
        "description": "开篇拆分 — 前段每一段分别承担什么功能",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "调开篇场景内容",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_2",
        "stage": "outline",
        "category": "new",
        "description": "场景推进 — 每个场景是否承担新信息或新压力",
        "source_ref": "templates/project/03_Outline.md",
        "fail_action": "加事件或删冗余",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_3",
        "stage": "outline",
        "category": "new",
        "description": "钩子布置 — 前段是否有足够继续读的悬念",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "补钩子，但别把每段都写成悬念模板",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_4",
        "stage": "outline",
        "category": "new",
        "description": "预期翻面 — 前几章是否真的打破了读者预期",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "前置反转，但要保留因果",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_5",
        "stage": "outline",
        "category": "new",
        "description": "场景颗粒度 — 有没有过长概述段需要拆开",
        "source_ref": "templates/project/03_Outline.md / PROJECT_RULES.md §6",
        "fail_action": "拆场景，别让概述吞掉现场",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_6",
        "stage": "outline",
        "category": "new",
        "description": "断点设计 — 场景结尾是否落在动作、信息或抉择上",
        "source_ref": "templates/project/03_Outline.md",
        "fail_action": "调截断点内容",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_7",
        "stage": "outline",
        "category": "new",
        "description": "截断形态 — 当前场景用的是不是最强的继续读方式",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/03_Outline.md",
        "fail_action": "选最强形态，但别脱离场景本身",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_8",
        "stage": "outline",
        "category": "new",
        "description": "情绪递进 — 是否存在连续场景情绪不变",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "加情绪递进",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_9",
        "stage": "outline",
        "category": "new",
        "description": "角色功能 — 配角是否只是送信息或推剧情",
        "source_ref": "templates/project/03_Outline.md / PROJECT_RULES.md §6",
        "fail_action": "给配角动机或重排场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.7 Scene Pressure Test — 原有 5 维度（评分型）+ 新增 5 项
    # =====================================================================
    {
        "id": "spt_D1",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "冲突强度 — 谁想要什么，谁在阻止",
        "source_ref": "templates/project/03_Outline.md / AI_WRITING_SOP.md：阶段 4.5",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D2",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "代价感 — 场景失败会失去什么",
        "source_ref": "templates/project/03_Outline.md / AI_WRITING_SOP.md：阶段 4.5",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D3",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "信息变化 — 场景结束后局势、认知或关系是否变化",
        "source_ref": "templates/project/03_Outline.md",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D4",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "主角决策 — 主角是否主动选择，而不是只是被动承受",
        "source_ref": "templates/project/03_Outline.md",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D5",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "结尾钩子 — 场景结束时是否还驱动下一场",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_new_1",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "场景密度 — 场景内是否有实质推进",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "加/删事件",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_2",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "场景情绪弧 — 入/出是否形成变化",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_structure.md",
        "fail_action": "调场景情绪弧",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_3",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "截断场景 — 结尾是否足够让人继续读",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "加强截断场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_4",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "截断形态 — 断点类型是否与当前场景最强信息变化匹配",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/03_Outline.md",
        "fail_action": "换更强形态，但保留前因",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_5",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "相邻场景递进 — 是否存在连续空转",
        "source_ref": "templates/project/03_Outline.md / PROJECT_RULES.md §6",
        "fail_action": "加情绪变化，不要让段落打平",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.8 Prototype — 原有 7 项 + 新增 6 项
    # =====================================================================
    {
        "id": "proto_T1",
        "stage": "prototype",
        "category": "original",
        "description": "开头是否够快、是否直接把卡片发动机启动",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/04_Prototype.md",
        "fail_action": "前置冲突",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T2",
        "stage": "prototype",
        "category": "original",
        "description": "冲突是否持续推进",
        "source_ref": "CONTENT_FRAMEWORK_writing.md",
        "fail_action": "加推进节点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T3",
        "stage": "prototype",
        "category": "original",
        "description": "中段是否掉速或开始概述化",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "加事件或删冗余",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T4",
        "stage": "prototype",
        "category": "original",
        "description": "反转是否有前因支撑",
        "source_ref": "templates/project/04_Prototype.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "补因果支撑",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T5",
        "stage": "prototype",
        "category": "original",
        "description": "角色是否开始工具化",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "给角色动机",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T6",
        "stage": "prototype",
        "category": "original",
        "description": "语言是否滑向提纲 prose",
        "source_ref": "CONTENT_FRAMEWORK_writing.md",
        "fail_action": "加场景感和细节",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T7",
        "stage": "prototype",
        "category": "original",
        "description": "正文放大后最危险的段落",
        "source_ref": "templates/project/04_Prototype.md / PROJECT_RULES.md §6",
        "fail_action": "标注风险，扩写时重点关注",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_1",
        "stage": "prototype",
        "category": "new",
        "description": "平台基线 — opening、推进节奏和情绪牵引是否符合 `target_platform`",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/04_Prototype.md",
        "fail_action": "按平台基线回修 Prototype",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_2",
        "stage": "prototype",
        "category": "new",
        "description": "对话承载 — 对话是否承担关系推进、信息变化或冲突推进",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/04_Prototype.md",
        "fail_action": "重写对话功能，不要只盯标点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_3",
        "stage": "prototype",
        "category": "new",
        "description": "对话推进 — 对话是否真正推动关系、信息或冲突",
        "source_ref": "CONTENT_FRAMEWORK_writing.md",
        "fail_action": "回修对话，让它承担推进职责",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_4",
        "stage": "prototype",
        "category": "new",
        "description": "写法偏移 — 是否开始只解释、不推进，或脱离平台基线",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "改回具体场面、推进动作和平台基线",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_5",
        "stage": "prototype",
        "category": "new",
        "description": "基线一致性 — 是否还遵守卡片锚点、平台基线和场景推进",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/04_Prototype.md",
        "fail_action": "逐条清理后再评估是否 rework",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_6",
        "stage": "prototype",
        "category": "new",
        "description": "opening 试写 — 试写开头后，是否真的立住吸引力",
        "source_ref": "templates/project/04_Prototype.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "调 opening 或回修开头",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.9 Expansion 单章压力测试 — 7 项（全部新增）
    # =====================================================================
    {
        "id": "exp_1",
        "stage": "expansion",
        "category": "new",
        "description": "场景推进 — 本章是否每个场景都产生实际变化",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/EXPANSION_CONTEXT.md",
        "fail_action": "加事件或情绪转折",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_2",
        "stage": "expansion",
        "category": "new",
        "description": "平台延续 — 扩写后是否仍延续 Prototype 确认的写法基线",
        "source_ref": "AI_WRITING_SOP.md：Expansion / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "按平台基线回修本章",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_3",
        "stage": "expansion",
        "category": "new",
        "description": "对话推进 — 对话是否继续承担关系、信息或冲突推进",
        "source_ref": "CONTENT_FRAMEWORK_writing.md",
        "fail_action": "回修对话，让它继续承担推进职责",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_4",
        "stage": "expansion",
        "category": "new",
        "description": "过渡控制 — 是否出现大段纯过渡或无推进",
        "source_ref": "PROJECT_RULES.md §6 / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "加冲突或新信息",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_5",
        "stage": "expansion",
        "category": "new",
        "description": "写法延续 — 是否仍在往前推事，而不是只解释或空喊情绪",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "改回平台基线后再继续",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_6",
        "stage": "expansion",
        "category": "new",
        "description": "失败模式反查 — 是否出现便利转折、角色工具化、情绪空转",
        "source_ref": "PROJECT_RULES.md §6 / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "对应修复，再判断是否 rework",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_7",
        "stage": "expansion",
        "category": "new",
        "description": "继承与更新 — EXPANSION_CONTEXT 是否已完整继承卡片/结构/大纲，并补了本场实际状态",
        "source_ref": "AI_WRITING_SOP.md：Expansion / templates/project/EXPANSION_CONTEXT.md",
        "fail_action": "先补完整继承和实际状态，再继续扩写",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.10 Review 全文压力测试 — 原有 5 项 + 新增 11 项
    # =====================================================================
    {
        "id": "review_R1",
        "stage": "review",
        "category": "original",
        "description": "便利型转折 — 关键转折有无前置支撑",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "回修对应场景，必要时回退上层",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R2",
        "stage": "review",
        "category": "original",
        "description": "角色工具化 — 配角有无自身动机",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/IDEA_CARD.md",
        "fail_action": "补角色弧，必要时回修结构",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R3",
        "stage": "review",
        "category": "original",
        "description": "情绪空转 — 连续多章无情绪递进",
        "source_ref": "CONTENT_FRAMEWORK_writing.md",
        "fail_action": "加情绪变化或回修 Outline",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R4",
        "stage": "review",
        "category": "original",
        "description": "文风漂移 — 前后文风是否一致",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/04_Prototype.md",
        "fail_action": "统一文风",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R5",
        "stage": "review",
        "category": "original",
        "description": "问题定级 — 属于扩写层、outline 层还是结构层",
        "source_ref": "PROJECT_RULES.md §3 / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "按层级回修",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_1",
        "stage": "review",
        "category": "new",
        "description": "体量完成度 — 是否达到当前确认范围，而不是半途收尾",
        "source_ref": "PROJECT_RULES.md §5 / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "扩写薄弱场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_2",
        "stage": "review",
        "category": "new",
        "description": "开篇兑现 — 开篇是否兑现了结构和平台预期",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / templates/project/04_Prototype.md",
        "fail_action": "改开篇，必要时回修 Prototype",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_3",
        "stage": "review",
        "category": "new",
        "description": "关键断点 — 关键场景的断点是否仍然成立",
        "source_ref": "templates/project/03_Outline.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "调整截断位置或回修场景顺序",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_4",
        "stage": "review",
        "category": "new",
        "description": "平台对齐 — 全文写法是否仍与 `target_platform` 一致",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / CONTENT_FRAMEWORK.md",
        "fail_action": "按平台对齐结果进入 rework / reject / hold",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_5",
        "stage": "review",
        "category": "new",
        "description": "情绪曲线 — 全文是否兑现结构阶段的情绪安排",
        "source_ref": "templates/project/02_Structure.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "修对应场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_6",
        "stage": "review",
        "category": "new",
        "description": "继续阅读动力 — 截断点是否还能支撑继续读",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "回修断点，并按 rework / reject / hold 分流",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_7",
        "stage": "review",
        "category": "new",
        "description": "红线终审 — 是否有任何必须回退的卡片或内容问题",
        "source_ref": "PROJECT_RULES.md §3 / templates/project/IDEA_CARD.md",
        "fail_action": "按问题级别进入 rework / reject / hold",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_8",
        "stage": "review",
        "category": "new",
        "description": "内容承载 — 是否有明显概述过量、信息堆叠或空转",
        "source_ref": "PROJECT_RULES.md §6 / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "补对话或描写，必要时回修段落",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_9",
        "stage": "review",
        "category": "new",
        "description": "入口定稿 — 标题与 opening 是否能作为最终入口",
        "source_ref": "templates/project/04_Prototype.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "重写标题或 opening，不要只修一句话",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_10",
        "stage": "review",
        "category": "new",
        "description": "写法终审 — 正文是否持续往前推事，而不是只解释或空喊情绪",
        "source_ref": "CONTENT_FRAMEWORK_writing.md / PROJECT_RULES.md §6",
        "fail_action": "按平台基线回修后再判定",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_11",
        "stage": "review",
        "category": "new",
        "description": "核心母题兑现 — `primary_motif` 是否在正文中真正落地",
        "source_ref": "templates/project/IDEA_CARD.md / CONTENT_FRAMEWORK_writing.md",
        "fail_action": "评估加强方向或回修母题",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
]

# ---------------------------------------------------------------------------
# 索引辅助
# ---------------------------------------------------------------------------

_CHECK_BY_ID: dict[str, dict[str, Any]] = {c["id"]: c for c in STAGE_CHECKS}
_CHECKS_BY_STAGE: dict[str, list[dict[str, Any]]] = {}
for _check in STAGE_CHECKS:
    _CHECKS_BY_STAGE.setdefault(_check["stage"], []).append(_check)


def get_checks_for_stage(stage: str) -> list[dict[str, Any]]:
    """返回指定阶段的全部检查定义（原有 + 新增）。"""
    return list(_CHECKS_BY_STAGE.get(stage, []))


def get_check_by_id(check_id: str) -> dict[str, Any] | None:
    """按 ID 查找单条检查定义。"""
    return _CHECK_BY_ID.get(check_id)
