"""
检查定义数据文件 — 10 个阶段的压力测试检查项。

从 docs/盐选压力测试_合并稿.md 第八节转录。
每条检查包含：id, stage, category, description, source_ref, fail_action, result_type, score_range, required。
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# 聚合评分阈值
# ---------------------------------------------------------------------------

KILLER_TEST_THRESHOLDS = {"fail": (0, 3), "rewrite": (4, 5), "pass": (6, 8)}
SCENE_PT_THRESHOLDS = {"fail": (0, 3), "risk": (4, 6), "pass": (7, 10)}

# ---------------------------------------------------------------------------
# 阶段检查定义
# ---------------------------------------------------------------------------

STAGE_CHECKS: list[dict[str, Any]] = [
    # =====================================================================
    # 8.1 Intake / Idea Fission（脑洞阶段）— 新增 4 项
    # =====================================================================
    {
        "id": "intake_new_1",
        "stage": "intake",
        "category": "new",
        "description": "红线 3.1 — 题材本身是否触红线",
        "source_ref": "三、红线 3.1",
        "fail_action": "直接换方向",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "intake_new_2",
        "stage": "intake",
        "category": "new",
        "description": "选题公式 — 是否命中「情感冲突 × 现实痛点 × 悬念」",
        "source_ref": "4.1 选题公式",
        "fail_action": "调整脑洞方向",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "intake_new_3",
        "stage": "intake",
        "category": "new",
        "description": "饱和预警 — 题材是否已同质化严重",
        "source_ref": "4.1 饱和预警",
        "fail_action": "加差异化元素或换赛道",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "intake_new_4",
        "stage": "intake",
        "category": "new",
        "description": "读者心理抓手 — 有没有至少 1 个核心抓手（爽/代入/吃瓜/信息差）",
        "source_ref": "4.5 读者心理抓手",
        "fail_action": "补抓手再往下",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.2 Killer Test — 原有 4 问（评分型）+ 新增 6 项
    # =====================================================================
    {
        "id": "kt_K1",
        "stage": "killer_test",
        "category": "original",
        "description": "故事还是点子？是否隐含一个会发生变化的过程",
        "source_ref": "8.2 K1",
        "fail_action": "暂缓或重写",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_K2",
        "stage": "killer_test",
        "category": "original",
        "description": "冲突天然还是硬造？脑洞本身会自然产生冲突吗",
        "source_ref": "8.2 K2",
        "fail_action": "暂缓或重写",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_K3",
        "stage": "killer_test",
        "category": "original",
        "description": "一句话好听还是展开也能打？写成场景仍有吸引力吗",
        "source_ref": "8.2 K3",
        "fail_action": "暂缓或重写",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_K4",
        "stage": "killer_test",
        "category": "original",
        "description": "是否靠高级感伪装？是靠宿命感/悲伤感/哲学感，还是真有叙事能量",
        "source_ref": "8.2 K4",
        "fail_action": "暂缓或重写",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "kt_new_1",
        "stage": "killer_test",
        "category": "new",
        "description": "开篇概念 — 前 100 字能否有冲突/异常事件",
        "source_ref": "1.2 开篇",
        "fail_action": "重设开篇事件",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_2",
        "stage": "killer_test",
        "category": "new",
        "description": "人物动机 — 「想要什么，为什么想要」能否一句话说清",
        "source_ref": "2.3 人物动机",
        "fail_action": "补动机",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_3",
        "stage": "killer_test",
        "category": "new",
        "description": "冲突来源 — 核心冲突是否依赖巧合或空降信息",
        "source_ref": "2.3 冲突来源",
        "fail_action": "补因果链",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_4",
        "stage": "killer_test",
        "category": "new",
        "description": "共鸣 — 目标读者能否联想到自身经历",
        "source_ref": "2.3 共鸣",
        "fail_action": "调人物处境",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_5",
        "stage": "killer_test",
        "category": "new",
        "description": "红线复查 — 题材确定后全部红线精确复查",
        "source_ref": "三、红线",
        "fail_action": "调整或放弃",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "kt_new_6",
        "stage": "killer_test",
        "category": "new",
        "description": "题材竞争力 — 在同类题材中有没有差异化记忆点",
        "source_ref": "4.1 题材竞争力",
        "fail_action": "加记忆点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.3 Premise Test — 原有 5 问 + 新增 4 项
    # =====================================================================
    {
        "id": "pt_P1",
        "stage": "premise_test",
        "category": "original",
        "description": "谁想达成什么",
        "source_ref": "8.3 P1",
        "fail_action": "补主角目标",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P2",
        "stage": "premise_test",
        "category": "original",
        "description": "为什么非要这么做",
        "source_ref": "8.3 P2",
        "fail_action": "补动机必要性",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P3",
        "stage": "premise_test",
        "category": "original",
        "description": "为什么不能用更简单的办法",
        "source_ref": "8.3 P3",
        "fail_action": "堵简单解",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P4",
        "stage": "premise_test",
        "category": "original",
        "description": "相关人为什么会配合",
        "source_ref": "8.3 P4",
        "fail_action": "补配角动机",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_P5",
        "stage": "premise_test",
        "category": "original",
        "description": "主角为什么不能直接离开、报警或求助",
        "source_ref": "8.3 P5",
        "fail_action": "堵退路",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_1",
        "stage": "premise_test",
        "category": "new",
        "description": "转折靠巧合 — 核心转折是否有前因支撑",
        "source_ref": "5.3 转折靠巧合",
        "fail_action": "补铺垫",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_2",
        "stage": "premise_test",
        "category": "new",
        "description": "反机制 — 主角是否只会听话，有没有反抗/挣扎",
        "source_ref": "2.3 反机制",
        "fail_action": "加内在冲突",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_3",
        "stage": "premise_test",
        "category": "new",
        "description": "成长弧 — 起点到终点有没有变化空间",
        "source_ref": "2.3 成长弧",
        "fail_action": "调人物起点或终点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "pt_new_4",
        "stage": "premise_test",
        "category": "new",
        "description": "优缺点 — 主角是否同时有优点和缺点",
        "source_ref": "2.3 优缺点",
        "fail_action": "补人物缺陷",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.4 Evaluation — 原有 4 项 + 新增 5 项
    # =====================================================================
    {
        "id": "eval_E1",
        "stage": "evaluation",
        "category": "original",
        "description": "吸睛度 — 题材本身能不能吸引点击",
        "source_ref": "8.4 E1",
        "fail_action": "调题材角度",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_E2",
        "stage": "evaluation",
        "category": "original",
        "description": "冲突张力 — 冲突是否有持续升级空间",
        "source_ref": "8.4 E2",
        "fail_action": "加冲突层次",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_E3",
        "stage": "evaluation",
        "category": "original",
        "description": "情绪价值 — 能给读者什么情绪体验",
        "source_ref": "8.4 E3",
        "fail_action": "明确情绪定位",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_E4",
        "stage": "evaluation",
        "category": "original",
        "description": "执行风险 — 是否容易写成便利型推进、工具人、提纲prose",
        "source_ref": "8.4 E4",
        "fail_action": "提前标注风险点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_1",
        "stage": "evaluation",
        "category": "new",
        "description": "饱和预警二次确认 — 同类作品近期密度",
        "source_ref": "4.1 饱和预警",
        "fail_action": "调差异化角度",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_2",
        "stage": "evaluation",
        "category": "new",
        "description": "付费性预判 — 这个故事能不能让人「必须看完」",
        "source_ref": "2.8 付费性综合",
        "fail_action": "加悬念层或调核心冲突",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_3",
        "stage": "evaluation",
        "category": "new",
        "description": "平台数据概念 — 目标完读率、付费转化率是否可期",
        "source_ref": "1.5 平台数据门槛",
        "fail_action": "评估是否值得继续投入",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_4",
        "stage": "evaluation",
        "category": "new",
        "description": "字数预估 — 这个故事展开后大概在什么字数区间",
        "source_ref": "1.1 字数规格",
        "fail_action": "调整故事体量",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "eval_new_5",
        "stage": "evaluation",
        "category": "new",
        "description": "标题方向 — 是否有高点击率标题的可能",
        "source_ref": "4.2 标题公式",
        "fail_action": "调故事卖点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.5 Structure — 原有 5 项 + 新增 6 项
    # =====================================================================
    {
        "id": "struct_S1",
        "stage": "structure",
        "category": "original",
        "description": "核心冲突、开篇爆点、30% 卡点、中段升级、终局回收",
        "source_ref": "8.5 S1",
        "fail_action": "补缺失节点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S2",
        "stage": "structure",
        "category": "original",
        "description": "大转折触发点 — 是人物选择推动还是作者安排推动",
        "source_ref": "8.5 S2",
        "fail_action": "改为人物驱动",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S3",
        "stage": "structure",
        "category": "original",
        "description": "情绪曲线 5 节点 — E1初始→E2扰动→E3升级→E4峰值→E5余味",
        "source_ref": "8.5 S3",
        "fail_action": "调节点位置",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S4",
        "stage": "structure",
        "category": "original",
        "description": "人物行为模式 — 核心行为模式/对谁细心对谁漠视/禁止矛盾行为",
        "source_ref": "8.5 S4",
        "fail_action": "补人物行为表",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_S5",
        "stage": "structure",
        "category": "original",
        "description": "核心 motif/设定清单 — 首次出现位置/需要回扣位置",
        "source_ref": "8.5 S5",
        "fail_action": "补伏笔表",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_1",
        "stage": "structure",
        "category": "new",
        "description": "三段式 — 开头冲突、中段升级、结尾反转是否清晰",
        "source_ref": "1.6 三段式",
        "fail_action": "调结构",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_2",
        "stage": "structure",
        "category": "new",
        "description": "主线 — 是否单一贯穿，有没有多条并行",
        "source_ref": "1.6 主线",
        "fail_action": "砍支线",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_3",
        "stage": "structure",
        "category": "new",
        "description": "截断位置预设 — 付费墙放在 35%-45% 的哪个场景",
        "source_ref": "1.4 截断位置",
        "fail_action": "调场景顺序",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_4",
        "stage": "structure",
        "category": "new",
        "description": "避免连续高潮 — 高潮之间有没有缓冲",
        "source_ref": "2.6 避免连续高潮",
        "fail_action": "插入过渡场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_5",
        "stage": "structure",
        "category": "new",
        "description": "铺垫变因果 — 关键伏笔是否已在结构中预设",
        "source_ref": "4.3 铺垫变因果",
        "fail_action": "补伏笔位置",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "struct_new_6",
        "stage": "structure",
        "category": "new",
        "description": "内容比例预设 — 对话/叙述/描写大致 1:1:1",
        "source_ref": "1.6 内容比例",
        "fail_action": "调场景类型分布",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.6 Outline — 原有 5 项 + 新增 9 项
    # =====================================================================
    {
        "id": "outline_O1",
        "stage": "outline",
        "category": "original",
        "description": "人物关系和关键动机梳理",
        "source_ref": "8.6 O1",
        "fail_action": "补关系线",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O2",
        "stage": "outline",
        "category": "original",
        "description": "每段承担的功能标注（推进冲突/释放爽点/揭露信息/制造钩子）",
        "source_ref": "8.6 O2",
        "fail_action": "补功能标注",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O3",
        "stage": "outline",
        "category": "original",
        "description": "标出最容易写空、写成概述的地方",
        "source_ref": "8.6 O3",
        "fail_action": "提前标注风险",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O4",
        "stage": "outline",
        "category": "original",
        "description": "每场景时间线、情绪位置入/出",
        "source_ref": "8.6 O4",
        "fail_action": "补场景情绪标注",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_O5",
        "stage": "outline",
        "category": "original",
        "description": "认知差追踪表（主角/读者/其他角色各知道什么）",
        "source_ref": "8.6 O5",
        "fail_action": "补认知差表",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_1",
        "stage": "outline",
        "category": "new",
        "description": "开篇逐级 — 前 50/100/200/300/1000 字各完成什么",
        "source_ref": "1.2 开篇逐级",
        "fail_action": "调开篇场景内容",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_2",
        "stage": "outline",
        "category": "new",
        "description": "节奏密度 — 每 600-800 字有没有情绪变化/新信息",
        "source_ref": "1.3 节奏密度",
        "fail_action": "加事件或删冗余",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_3",
        "stage": "outline",
        "category": "new",
        "description": "钩子密度 — 前 3 章/3000 字至少 3 个钩子",
        "source_ref": "1.3 钩子密度",
        "fail_action": "补钩子",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_4",
        "stage": "outline",
        "category": "new",
        "description": "三章必反转 — 前 3 章内有没有打破读者预期",
        "source_ref": "1.3 三章必反转",
        "fail_action": "前置反转",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_5",
        "stage": "outline",
        "category": "new",
        "description": "场景密度 — 每章不超过 3 个场景",
        "source_ref": "1.6 场景密度",
        "fail_action": "拆场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_6",
        "stage": "outline",
        "category": "new",
        "description": "截断位置精确 — 截断场景的最后一句是否有超级悬念",
        "source_ref": "1.4 截断位置",
        "fail_action": "调截断点内容",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_7",
        "stage": "outline",
        "category": "new",
        "description": "付费点截断形态 — 属于哪种（转折/情绪/打断/揭秘/抉择）",
        "source_ref": "2.5 付费点截断形态",
        "fail_action": "选最强形态",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_8",
        "stage": "outline",
        "category": "new",
        "description": "情绪空转 — 有没有连续多个场景情绪不递进",
        "source_ref": "5.3 情绪空转",
        "fail_action": "加情绪递进",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "outline_new_9",
        "stage": "outline",
        "category": "new",
        "description": "角色工具化 — 配角是否只负责送信息",
        "source_ref": "5.3 角色工具化",
        "fail_action": "给配角动机",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.7 Scene Pressure Test — 原有 5 维度（评分型）+ 新增 5 项
    # =====================================================================
    {
        "id": "spt_D1",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "冲突强度 — 谁想要什么？谁在阻止？",
        "source_ref": "8.7 D1",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D2",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "代价感 — 主角在这个场景失败会失去什么？",
        "source_ref": "8.7 D2",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D3",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "信息变化 — 场景结束后局势/认知/关系发生了什么变化？",
        "source_ref": "8.7 D3",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D4",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "主角决策 — 主角做了什么选择？还是只是被动承受？",
        "source_ref": "8.7 D4",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_D5",
        "stage": "scene_pressure_test",
        "category": "original",
        "description": "结尾钩子 — 场景结束时读者为什么要继续读？",
        "source_ref": "8.7 D5",
        "fail_action": "回修 Outline",
        "result_type": "scored",
        "score_range": (0, 2),
        "required": True,
    },
    {
        "id": "spt_new_1",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "节奏密度（精确到场景）— 场景内是否有 600-800 字情绪变化",
        "source_ref": "1.3 节奏密度",
        "fail_action": "加/删事件",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_2",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "情绪曲线（场景级别）— 每场景情绪入/出是否有变化",
        "source_ref": "2.6 情绪曲线",
        "fail_action": "调场景情绪弧",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_3",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "截断场景特写 — 截断场景是否满足「无法忍受不看下去」",
        "source_ref": "1.4 截断场景",
        "fail_action": "加强截断场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_4",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "截断形态 — 属于哪种（转折/情绪/打断/揭秘/抉择），是否最强",
        "source_ref": "2.5 截断形态",
        "fail_action": "换更强形态",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "spt_new_5",
        "stage": "scene_pressure_test",
        "category": "new",
        "description": "情绪空转 — 相邻场景是否情绪不递进",
        "source_ref": "5.3 情绪空转",
        "fail_action": "加情绪变化",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.8 Prototype — 原有 7 项 + 新增 6 项
    # =====================================================================
    {
        "id": "proto_T1",
        "stage": "prototype",
        "category": "original",
        "description": "开头是否够快",
        "source_ref": "8.8 T1",
        "fail_action": "前置冲突",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T2",
        "stage": "prototype",
        "category": "original",
        "description": "冲突是否持续推进",
        "source_ref": "8.8 T2",
        "fail_action": "加推进节点",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T3",
        "stage": "prototype",
        "category": "original",
        "description": "中段是否掉速",
        "source_ref": "8.8 T3",
        "fail_action": "加事件或删冗余",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T4",
        "stage": "prototype",
        "category": "original",
        "description": "反转是否成立",
        "source_ref": "8.8 T4",
        "fail_action": "补因果支撑",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T5",
        "stage": "prototype",
        "category": "original",
        "description": "角色是否开始工具化",
        "source_ref": "8.8 T5",
        "fail_action": "给角色动机",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T6",
        "stage": "prototype",
        "category": "original",
        "description": "语言是否滑向提纲 prose",
        "source_ref": "8.8 T6",
        "fail_action": "加场景感和细节",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_T7",
        "stage": "prototype",
        "category": "original",
        "description": "正文放大后最危险的段落",
        "source_ref": "8.8 T7",
        "fail_action": "标注风险，扩写时重点关注",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_1",
        "stage": "prototype",
        "category": "new",
        "description": "叙述风格 — 人称、语言、句式、段落、代入感",
        "source_ref": "2.1 叙述风格",
        "fail_action": "调文风",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_2",
        "stage": "prototype",
        "category": "new",
        "description": "对话标点 — 是否使用「」",
        "source_ref": "2.1 对话标点",
        "fail_action": "统一替换",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_3",
        "stage": "prototype",
        "category": "new",
        "description": "对话质量 — 区分度、潜台词、动作配合",
        "source_ref": "2.4 对话质量",
        "fail_action": "改对话",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_4",
        "stage": "prototype",
        "category": "new",
        "description": "AI 腔/翻译腔 — 是否有套路表达",
        "source_ref": "5.2 AI 写作翻车",
        "fail_action": "去 AI 味",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_5",
        "stage": "prototype",
        "category": "new",
        "description": "去 AI 味快速扫描 — 6.1 结构与表达 + 6.2 中文小说专属",
        "source_ref": "六、去 AI 味",
        "fail_action": "逐条清理",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "proto_new_6",
        "stage": "prototype",
        "category": "new",
        "description": "导语设计 — 试写导语，验证吸引力",
        "source_ref": "2.2 导语设计",
        "fail_action": "调导语",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.9 Expansion 单章压力测试 — 7 项（全部新增）
    # =====================================================================
    {
        "id": "exp_1",
        "stage": "expansion",
        "category": "new",
        "description": "节奏密度（本章范围）— 每 600-800 字是否有情绪变化",
        "source_ref": "1.3 节奏密度",
        "fail_action": "加事件或情绪转折",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_2",
        "stage": "expansion",
        "category": "new",
        "description": "叙述风格 — 句式、段落、口语化",
        "source_ref": "2.1 叙述风格",
        "fail_action": "逐段调",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_3",
        "stage": "expansion",
        "category": "new",
        "description": "对话质量 — 本章对话是否有区分度和潜台词",
        "source_ref": "2.4 对话质量",
        "fail_action": "改对话",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_4",
        "stage": "expansion",
        "category": "new",
        "description": "完读率保障 — 本章是否有 >2000 字纯过渡",
        "source_ref": "2.7 完读率保障",
        "fail_action": "加冲突/新信息",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_5",
        "stage": "expansion",
        "category": "new",
        "description": "去 AI 味全项 — 6.1 + 6.2 + 6.3 逐条过",
        "source_ref": "六、去 AI 味",
        "fail_action": "逐条清理",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_6",
        "stage": "expansion",
        "category": "new",
        "description": "失败模式反向检查 — 5.2/5.3 全部扫描",
        "source_ref": "5.2/5.3 失败模式",
        "fail_action": "对应修复",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "exp_7",
        "stage": "expansion",
        "category": "new",
        "description": "与前文连贯性 — EXPANSION_CONTEXT 参照表对照",
        "source_ref": "项目规则",
        "fail_action": "修正断裂处",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },

    # =====================================================================
    # 8.10 Review 全文压力测试 — 原有 5 项 + 新增 11 项
    # =====================================================================
    {
        "id": "review_R1",
        "stage": "review",
        "category": "original",
        "description": "便利型转折 — 关键转折有无前置支撑",
        "source_ref": "8.10 R1",
        "fail_action": "回修对应场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R2",
        "stage": "review",
        "category": "original",
        "description": "角色工具化 — 配角有无自身动机",
        "source_ref": "8.10 R2",
        "fail_action": "补角色弧",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R3",
        "stage": "review",
        "category": "original",
        "description": "情绪空转 — 连续多章无情绪递进",
        "source_ref": "8.10 R3",
        "fail_action": "加情绪变化",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R4",
        "stage": "review",
        "category": "original",
        "description": "文风漂移 — 前后文风是否一致",
        "source_ref": "8.10 R4",
        "fail_action": "统一文风",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_R5",
        "stage": "review",
        "category": "original",
        "description": "问题定级 — 属于扩写层、outline 层还是结构层",
        "source_ref": "8.10 R5",
        "fail_action": "按层级回修",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_1",
        "stage": "review",
        "category": "new",
        "description": "字数规格 — 总字数是否达标",
        "source_ref": "1.1 字数规格",
        "fail_action": "扩写薄弱场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_2",
        "stage": "review",
        "category": "new",
        "description": "开篇逐级 — 50/100/200/300/1000 实测",
        "source_ref": "1.2 开篇逐级",
        "fail_action": "改开篇",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_3",
        "stage": "review",
        "category": "new",
        "description": "截断位置 — 实测是否在 35%-45%",
        "source_ref": "1.4 截断位置",
        "fail_action": "调整截断位置",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_4",
        "stage": "review",
        "category": "new",
        "description": "平台数据预估 — 完读率、付费转化率",
        "source_ref": "1.5 平台数据门槛",
        "fail_action": "评估整体调整方向",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_5",
        "stage": "review",
        "category": "new",
        "description": "情绪曲线（全文）— 画出完整曲线，找平原和断崖",
        "source_ref": "2.6 情绪曲线",
        "fail_action": "修对应场景",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_6",
        "stage": "review",
        "category": "new",
        "description": "付费性综合 — 截断点付费冲动、信息差持续",
        "source_ref": "2.8 付费性综合",
        "fail_action": "调整免费/付费内容分配",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_7",
        "stage": "review",
        "category": "new",
        "description": "红线终审 — 全部红线最终确认",
        "source_ref": "三、红线",
        "fail_action": "一票否决，必须修到通过",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_8",
        "stage": "review",
        "category": "new",
        "description": "内容比例 — 对话/叙述/描写比例是否合理",
        "source_ref": "1.6 内容比例",
        "fail_action": "补对话或描写",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_9",
        "stage": "review",
        "category": "new",
        "description": "导语定稿 — 导语是否具象、有悬念",
        "source_ref": "2.2 导语设计",
        "fail_action": "重写导语",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_10",
        "stage": "review",
        "category": "new",
        "description": "去 AI 味全项终审 — 6.1 + 6.2 + 6.3 逐条全文扫描",
        "source_ref": "六、去 AI 味",
        "fail_action": "逐条清理",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
    {
        "id": "review_new_11",
        "stage": "review",
        "category": "new",
        "description": "爆款叙事特征 — 终审是否命中核心爆款特征",
        "source_ref": "4.3 爆款叙事特征",
        "fail_action": "评估加强方向",
        "result_type": "pass_fail",
        "score_range": None,
        "required": True,
    },
]

# ---------------------------------------------------------------------------
# 索引辅助
# ---------------------------------------------------------------------------

_CHECK_BY_ID: dict[str, dict[str, Any]] = {c["id"]: c for c in STAGE_CHECKS}
_CHECKS_BY_STAGE: dict[str, list[dict[str, Any]]] = {}
for _check in STAGE_CHECKS:
    _CHECKS_BY_STAGE.setdefault(_check["stage"], []).append(_check)


def get_checks_for_stage(stage: str) -> list[dict[str, Any]]:
    """返回指定阶段的全部检查定义（原有 + 新增）。"""
    return list(_CHECKS_BY_STAGE.get(stage, []))


def get_check_by_id(check_id: str) -> dict[str, Any] | None:
    """按 ID 查找单条检查定义。"""
    return _CHECK_BY_ID.get(check_id)
